// Mocks generated by Mockito 5.4.6 from annotations
// in cellit/test/domain/usecases/expense_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cellit/core/common/result.dart' as _i4;
import 'package:cellit/domain/entities/expense_entity.dart' as _i6;
import 'package:cellit/domain/repositories/expense_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i2.ExpenseRepository {
  MockExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<int>> syncAllUserExpenses(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncAllUserExpenses, [userId]),
            returnValue: _i3.Future<_i4.Result<int>>.value(
              _i5.dummyValue<_i4.Result<int>>(
                this,
                Invocation.method(#syncAllUserExpenses, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<int>>);

  @override
  _i3.Future<_i4.Result<_i6.ExpenseEntity?>> getExpense(int? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#getExpense, [expenseId]),
            returnValue: _i3.Future<_i4.Result<_i6.ExpenseEntity?>>.value(
              _i5.dummyValue<_i4.Result<_i6.ExpenseEntity?>>(
                this,
                Invocation.method(#getExpense, [expenseId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.ExpenseEntity?>>);

  @override
  _i3.Future<_i4.Result<int>> createExpense(_i6.ExpenseEntity? expense) =>
      (super.noSuchMethod(
            Invocation.method(#createExpense, [expense]),
            returnValue: _i3.Future<_i4.Result<int>>.value(
              _i5.dummyValue<_i4.Result<int>>(
                this,
                Invocation.method(#createExpense, [expense]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<int>>);

  @override
  _i3.Future<_i4.Result<void>> updateExpense(_i6.ExpenseEntity? expense) =>
      (super.noSuchMethod(
            Invocation.method(#updateExpense, [expense]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i5.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateExpense, [expense]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteExpense(int? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpense, [expenseId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i5.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteExpense, [expenseId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i6.ExpenseEntity>>> getUserExpenses(
    String? userId, {
    String? orderBy,
    String? sortBy,
    int? limit,
    int? offset,
    String? contains,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserExpenses,
              [userId],
              {
                #orderBy: orderBy,
                #sortBy: sortBy,
                #limit: limit,
                #offset: offset,
                #contains: contains,
              },
            ),
            returnValue: _i3.Future<_i4.Result<List<_i6.ExpenseEntity>>>.value(
              _i5.dummyValue<_i4.Result<List<_i6.ExpenseEntity>>>(
                this,
                Invocation.method(
                  #getUserExpenses,
                  [userId],
                  {
                    #orderBy: orderBy,
                    #sortBy: sortBy,
                    #limit: limit,
                    #offset: offset,
                    #contains: contains,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i6.ExpenseEntity>>>);
}
